[package]
authors = ["Christoph Groß <caemor@mailbox.org>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "An embedded-hal based driver for ePaper displays from Waveshare formerly published as eink-waveshare-rs"
documentation = "https://docs.rs/epd-waveshare"
homepage = "https://github.com/caemor/epd-waveshare"
keywords = ["ePaper", "Display", "epd", "eink"]
license = "ISC"
name = "epd-waveshare"
readme = "README.md"
repository = "https://github.com/Caemor/epd-waveshare.git"
version = "0.5.0"
edition = "2018"

[badges]
# travis-ci = { repository = "caemor/epd-waveshare" }

[dependencies]
embedded-graphics = { version = "0.7.1", optional = true }
embedded-graphics-core = { version = "0.3.2", optional = true }
embedded-hal = "=1.0.0-alpha.4"
bit_field = "0.10.1"

[dev-dependencies]
linux-embedded-hal = { git = "https://github.com/rust-embedded/linux-embedded-hal", rev = "b930d32" }
embedded-hal-mock = "0.7"

[features]
default = ["graphics"]

graphics = ["embedded-graphics","embedded-graphics-core"]

# Offers an alternative fast full lut for type_a displays, but the refreshed screen isnt as clean looking
type_a_alternative_faster_lut = []
